steps:
- name: golang
  args: ['make', 'test']
  waitFor: ['-']
- name: golang
  env:
  - 'GOOS=linux'
  - 'GOARCH=amd64'
  args: ['make', 'build']
artifacts:
  objects:
    location: gs://${PROJECT_ID}-builds/shifter-server/${$BRANCH_NAME}
    paths: ['shifter_*']