version: "3"
services:
  shifter-ui:
    container_name: shifter_ui
    domainname: shifter.local
    image: gcr.io/shifter-ui-lz-002/shifter-ui:v0.0.1-dev
    environment:
      SHIFTER_SERVER_ENDPOINT: "http://localhost:9091/api/v1"
    ports:
      - 9090:8080
    links:
      - "shifter-server:shifter-server.local"
    networks:
      - shifter-network
  shifter-server:
    container_name: shifter_server
    domainname: shifter-server.local
    image: images.shifter.cloud/shifter:latest
    entrypoint: ["./shifter", "server"]
    ports:
      - 9091:8080
    networks:
      - shifter-network
networks:
  shifter-network:
